language: go
go_import_path: github.com/meitu/titan

go:
    - "1.11.4"

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script: 
    - make coverage
    - $HOME/gopath/bin/goveralls -coverprofile=cover.cov -service=travis-ci
