version: '2.1'

services:
  pd0:
    image: pingcap/pd:latest
    ports:
      - "2379"
    volumes:
      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd0
      - --log-file=/logs/pd0.log
    restart: on-failure
  
  tikv0:
    image: pingcap/tikv:latest
    volumes:
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379
      - --log-file=/logs/tikv0.log
    depends_on:
      - "pd0"
    restart: on-failure

  titan:
    image: meitu/titan
    ports:
      - "7369:7369"
    command:
      - --pd-addrs=tikv://pd0:2379
    depends_on:
      - "tikv0"
    restart: on-failure    
